# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    h2:
      console:
        enabled: true
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            maximum-pool-size: 50
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test
        username: root
        password: root

# --- server
server:
  port: 8080
  tomcat:
    max-threads: 20
    max-connections: 20000
mybatis:
  typeAliasesPackage: com.shuangye.freemarker.pojo
  mapperLocations: classpath:mapper/*.xml

jasypt:
  encryptor:
    password: hzObserveriai


