# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            maximum-pool-size: 50
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
    jpa:
      hibernate:
        ddl-auto: update
server:
  tomcat:
    max-threads: 20
    max-connections: 20000





